import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

type Props = {};

function AboutPage({}: Props) {
  return <div>About Page</div>;
}

export default AboutPage;
