import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next.js ",
    template: "%s | Fatma",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "red" }}>
          <p>This is header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "red" }}>
          <p>This is footer</p>
        </footer>
      </body>
    </html>
  );
}
